
version: '3'

volumes:
  grafana-data:
    driver: local
  influxdb-data:

services:
  grafana:
    image: grafana/grafana-oss:8.5.22
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
  influxdb:
    container_name: influxdb
    image: influxdb:2.6.1
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
    restart: always
